# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: healthcheck.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'healthcheck.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11healthcheck.proto\x12\x0bhealthcheck\"%\n\x12HealthCheckMessage\x12\x0f\n\x07message\x18\x01 \x01(\t2d\n\x0bHealthCheck\x12U\n\x0fSendHealthCheck\x12\x1f.healthcheck.HealthCheckMessage\x1a\x1f.healthcheck.HealthCheckMessage\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'healthcheck_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHCHECKMESSAGE']._serialized_start=34
  _globals['_HEALTHCHECKMESSAGE']._serialized_end=71
  _globals['_HEALTHCHECK']._serialized_start=73
  _globals['_HEALTHCHECK']._serialized_end=173
# @@protoc_insertion_point(module_scope)
